// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnLkxcBHxeaOR1Jo4bAGU-pejESJdaZ6Q',
    appId: '1:265453770068:web:82544b59096207fe3c64c1',
    messagingSenderId: '265453770068',
    projectId: 'food-tracker-414517',
    authDomain: 'food-tracker-414517.firebaseapp.com',
    storageBucket: 'food-tracker-414517.appspot.com',
    measurementId: 'G-0T1ZSGHJ7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7_KTsO2aTJLMC1XM2xu-Cu0buj85nX4k',
    appId: '1:265453770068:android:a29873bb5d72887a3c64c1',
    messagingSenderId: '265453770068',
    projectId: 'food-tracker-414517',
    storageBucket: 'food-tracker-414517.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRosMOB3W0ew2J4_hJiTSDJvCEo7X_LAI',
    appId: '1:265453770068:ios:3b61ebf68ecea8673c64c1',
    messagingSenderId: '265453770068',
    projectId: 'food-tracker-414517',
    storageBucket: 'food-tracker-414517.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
